[build]
  command = "npm run dist"
  functions = "dist/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  "slack-events" = { timeout = 10 }
  "generate-alt-text" = { timeout = 26 }

